services:
  web:
    build: ./web
    ports:
      - "80:80"
    volumes:
      - ./web:/app
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:8081"
      NEXT_PUBLIC_BACKEND_SERVER: "http://backend:8081"
    depends_on:
      - backend
    networks:
      - texttitannet

  backend:
    build: ./backend
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
    environment:
      HOST: "0.0.0.0"
      LLM_PROVIDER: groq
      LLM_MODEL: llama3-70b-8192
      LLM_API_TOKEN: "your-api-token-here"
      REDIS_SERVER: "db"
      REDIS_PORT: 6379
    depends_on:
      - db
    networks:
      - texttitannet

  db:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /data/redis-data:/data
    networks:
      - texttitannet

networks:
  texttitannet:
    driver: bridge